const requestedVersion = new URLSearchParams(window.location.search).get("version") || "1";
const version = window.brandPresentations?.[requestedVersion] ? requestedVersion : "1";
const c = window.brandPresentations?.[version] || window.brandContent;
const $ = (id) => document.getElementById(id);
document.title = `${c.name} — ${c.presentationLabel} | Brand Presentation`;
$("presentationLabel").textContent = c.presentationLabel;
document.querySelectorAll("[data-version]").forEach((link) => link.classList.toggle("is-active", link.dataset.version === version));
$("brandName").textContent = c.name;
$("nativeName").textContent = c.nativeName;
$("tagline").textContent = c.tagline;
$("intro").textContent = c.intro;
$("positioning").textContent = c.positioning;
$("conceptTitle").textContent = c.conceptTitle;
$("concept").textContent = c.concept;
$("typeNames").textContent = `${c.typography.display} + ${c.typography.body}`;
$("typeNote").textContent = c.typography.note;
$("referenceTypes").textContent = `${c.typography.display} / ${c.typography.body}`;
const toast = document.querySelector(".toast");
const copy = async (hex) => { try { await navigator.clipboard.writeText(hex); toast.textContent = `${hex} copied`; toast.classList.add("show"); setTimeout(() => toast.classList.remove("show"), 1800); } catch { toast.textContent = hex; toast.classList.add("show"); } };
const swatchMarkup = (color) => `<button class="swatch" style="--swatch:${color.hex}" data-hex="${color.hex}" type="button"><span class="colour"></span><span class="swatch-detail"><b>${color.name}</b><span>${color.hex}</span><small>${color.usage}</small></span></button>`;
$("swatches").innerHTML = c.colors.map(swatchMarkup).join("");
$("referenceSwatches").innerHTML = c.colors.map(swatchMarkup).join("");
document.querySelectorAll("[data-hex]").forEach((item) => item.addEventListener("click", () => copy(item.dataset.hex)));
$("applicationGrid").innerHTML = c.applications.map((a, index) => `<article class="application-card card-${index + 1}"><img src="${a.image}" alt="La Luna ${a.title} mockup" /><div class="application-copy"><h3>${a.title}</h3><p>${a.description}</p></div></article>`).join("");
$("lifestyleGrid").innerHTML = c.lifestyle.map((item, index) => `<article class="lifestyle-card lifestyle-${index + 1}"><img src="${item.image}" alt="La Luna lifestyle: ${item.title}" /><div><span>0${index + 1}</span><h3>${item.title}</h3><p>${item.description}</p></div></article>`).join("");
$("downloadList").innerHTML = c.downloads.map((d) => `<a class="download" href="${d.file}"><span><b>${d.label}</b><small>${d.note}</small></span><span>Download</span></a>`).join("");
const reference = document.querySelector(".reference");
document.querySelector(".reference-toggle").addEventListener("click", () => { reference.classList.add("open"); reference.setAttribute("aria-hidden", "false"); });
document.querySelector(".close-reference").addEventListener("click", () => { reference.classList.remove("open"); reference.setAttribute("aria-hidden", "true"); });
